#!/usr/bin/env sh
#
# Generate list of PIA VPN servers for NixOS module.
# Inspired by the pia-nm.sh[1] script.
#
# [1] https://www.privateinternetaccess.com/installer/pia-nm.sh

set -e

error() {
    echo "$@" >&2
    exit 1
}

thisfile=$(readlink -f -- "$0")
thisdir=$(dirname "$thisfile")
outputfile="$thisdir/pia-generated-server-list.nix"
IFS=$(echo)
servers=$(curl -Ss "https://www.privateinternetaccess.com/vpninfo/servers?version=24" | head -1)

if [ -z "$servers" ]; then
    error "Failed to download server list, aborting."
fi

servers=$(python2.7 <<EOF
import sys
import json
data = json.loads('$servers')

for k in data.keys():
    if k != "info":
        print data[k]["dns"] + ':' + data[k]["name"]
EOF
)

printf "# Generated by $thisfile\n\n" > "$outputfile"
printf "[\n" >> "$outputfile"
echo "$servers" | while read server; do
    name="PIA - "$(echo "$server" | cut -d: -f2)
    host=$(echo "$server" | cut -d: -f1)

    cat <<EOF >> "$outputfile"
  { id = "$name";
    uuid = "$(uuid -v 5 ns:URL "$name-$host")";
    remote = "$host";
  }
EOF
done
printf "]" >> "$outputfile"

echo "Generated $(echo "$servers" | wc -l) server entries in $outputfile"
