# Generated by /etc/nixos/options/pia/pia-server-list-generator.sh

[
  { id = "PIA - Mexico";
    uuid = "4b1ccfa9-3457-5ea4-824a-0d86d78f40e9";
    remote = "mexico.privateinternetaccess.com";
  }
  { id = "PIA - CA Toronto";
    uuid = "80a635f8-df93-56f2-a570-65899ba599bb";
    remote = "ca-toronto.privateinternetaccess.com";
  }
  { id = "PIA - CA Montreal";
    uuid = "94380df4-dd68-5446-8ce2-c0a7e6d60c49";
    remote = "ca.privateinternetaccess.com";
  }
  { id = "PIA - India";
    uuid = "48e0ff64-2a90-516c-956a-31d0c27be403";
    remote = "in.privateinternetaccess.com";
  }
  { id = "PIA - US Florida";
    uuid = "f7c94a50-de0e-5eab-9dd0-25b9ba02fef0";
    remote = "us-florida.privateinternetaccess.com";
  }
  { id = "PIA - UK Southampton";
    uuid = "2575a50f-42fe-569f-9045-42643143f922";
    remote = "uk-southampton.privateinternetaccess.com";
  }
  { id = "PIA - Japan";
    uuid = "632ed90a-bf6a-555f-a556-de63e62bdca7";
    remote = "japan.privateinternetaccess.com";
  }
  { id = "PIA - Turkey";
    uuid = "e2349345-5e54-54ca-a641-a08fc45c59b4";
    remote = "turkey.privateinternetaccess.com";
  }
  { id = "PIA - Netherlands";
    uuid = "d2a54487-3987-56a3-bdb7-688635876001";
    remote = "nl.privateinternetaccess.com";
  }
  { id = "PIA - Norway";
    uuid = "94ed319f-8dcc-5c35-abc2-d1c0df8f267a";
    remote = "no.privateinternetaccess.com";
  }
  { id = "PIA - AU Melbourne";
    uuid = "f8637490-de9e-5a76-94dd-6b40b6d1dbe9";
    remote = "aus-melbourne.privateinternetaccess.com";
  }
  { id = "PIA - New Zealand";
    uuid = "13aaa4db-f761-57d3-99de-2582f860efdb";
    remote = "nz.privateinternetaccess.com";
  }
  { id = "PIA - France";
    uuid = "ad239203-0b0e-5649-b8e6-57427d738eb8";
    remote = "france.privateinternetaccess.com";
  }
  { id = "PIA - AU Sydney";
    uuid = "1be63659-00c4-5e82-bd7e-0243af558ee3";
    remote = "aus.privateinternetaccess.com";
  }
  { id = "PIA - Ireland";
    uuid = "c8d2d518-57e1-5e27-948f-3fe73b0eb400";
    remote = "ireland.privateinternetaccess.com";
  }
  { id = "PIA - Romania";
    uuid = "4d375e8d-b950-5d95-93ea-f854e0c48f61";
    remote = "ro.privateinternetaccess.com";
  }
  { id = "PIA - Brazil";
    uuid = "f9db3ea9-d0ba-580d-91e0-7a21f2b6f6a9";
    remote = "brazil.privateinternetaccess.com";
  }
  { id = "PIA - Israel";
    uuid = "afc147bb-ae90-5922-8162-e0276ea85760";
    remote = "israel.privateinternetaccess.com";
  }
  { id = "PIA - US Midwest";
    uuid = "9ab0eef6-3e3a-5cd8-936b-2518e28ef9b6";
    remote = "us-midwest.privateinternetaccess.com";
  }
  { id = "PIA - US California";
    uuid = "37ac009c-5cc0-5cfc-a2ec-f067c7e0b212";
    remote = "us-california.privateinternetaccess.com";
  }
  { id = "PIA - Hong Kong";
    uuid = "708d716c-923f-55d7-bd0f-aced817bb589";
    remote = "hk.privateinternetaccess.com";
  }
  { id = "PIA - Germany";
    uuid = "b744d855-d4cc-52b9-aa24-9bee159c0109";
    remote = "germany.privateinternetaccess.com";
  }
  { id = "PIA - Finland";
    uuid = "51829104-98b9-5649-850b-37eb33e21f3a";
    remote = "fi.privateinternetaccess.com";
  }
  { id = "PIA - US Chicago";
    uuid = "8cf137b6-bea8-5d2b-9687-b0976b8a5341";
    remote = "us-chicago.privateinternetaccess.com";
  }
  { id = "PIA - US Silicon Valley";
    uuid = "7f261a73-9487-5d7f-95ee-cb798a2dc904";
    remote = "us-siliconvalley.privateinternetaccess.com";
  }
  { id = "PIA - US New York City";
    uuid = "9e3f0be2-87eb-5352-a321-23d22bf0d85e";
    remote = "us-newyorkcity.privateinternetaccess.com";
  }
  { id = "PIA - US Texas";
    uuid = "0b5cb308-1d16-56ad-830c-6253b475f4df";
    remote = "us-texas.privateinternetaccess.com";
  }
  { id = "PIA - Italy";
    uuid = "b25088c7-3746-5d1d-92c0-79799f5ff80c";
    remote = "italy.privateinternetaccess.com";
  }
  { id = "PIA - South Korea";
    uuid = "e914f6a5-3b19-58a2-bd39-bdf3ea36f343";
    remote = "kr.privateinternetaccess.com";
  }
  { id = "PIA - Sweden";
    uuid = "c24581b8-69a1-5fd0-9100-56f5f5010944";
    remote = "sweden.privateinternetaccess.com";
  }
  { id = "PIA - US West";
    uuid = "c881ad44-b2b6-51d2-b7e3-373b680554c2";
    remote = "us-west.privateinternetaccess.com";
  }
  { id = "PIA - US East";
    uuid = "37a27719-7ebd-500a-9a7b-4daa017bb27d";
    remote = "us-east.privateinternetaccess.com";
  }
  { id = "PIA - UK London";
    uuid = "1bbd385a-6d03-5661-9871-bca00b9cf66f";
    remote = "uk-london.privateinternetaccess.com";
  }
  { id = "PIA - Denmark";
    uuid = "5a5703fc-b960-516a-a786-9b59200ee52f";
    remote = "denmark.privateinternetaccess.com";
  }
  { id = "PIA - Switzerland";
    uuid = "961a068b-71a0-5440-aa43-0f63e443cf34";
    remote = "swiss.privateinternetaccess.com";
  }
  { id = "PIA - US Seattle";
    uuid = "be257767-864c-560a-8b30-b66c3270a312";
    remote = "us-seattle.privateinternetaccess.com";
  }
  { id = "PIA - Singapore";
    uuid = "a92761e1-d0b1-5630-98b5-6b5f225d364a";
    remote = "sg.privateinternetaccess.com";
  }
]